import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/layout/Header";
import Footer from "@/src/layout/Footer";

const hiraginoFontFamily = `"Yu Micho", "Hiragino Mincho ProN", serif`;

export const metadata: Metadata = {
  title: "BLM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" style={{ fontFamily: hiraginoFontFamily }}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
