import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/layout/Header";
import Footer from "@/src/layout/Footer";
import styles from "./Root.module.css";

const hiraginoFontFamily = `"Yu Micho", "Hiragino Mincho ProN", serif`;

export const metadata: Metadata = {
  title: "BLM",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font-root">
        <div className={styles.pageContainer}>
          <Header />
          <main className={styles.content}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
