# Generated by Django 6.0.2 on 2026-02-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardProps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=100)),
                ("product_color", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=100)),
                ("product_description", models.TextField()),
                ("product_price", models.PositiveIntegerField()),
                (
                    "image_src",
                    models.ImageField(blank=True, null=True, upload_to="homepage"),
                ),
                ("link", models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactProps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("instagram", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                (
                    "image_src1",
                    models.ImageField(blank=True, null=True, upload_to="homepage"),
                ),
                (
                    "image_src2",
                    models.ImageField(blank=True, null=True, upload_to="homepage"),
                ),
                (
                    "image_src3",
                    models.ImageField(blank=True, null=True, upload_to="homepage"),
                ),
                ("content", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_choice",
                    models.CharField(
                        choices=[("text", "Text"), ("link", "Link")], max_length=100
                    ),
                ),
                ("content", models.TextField()),
                ("href", models.URLField(blank=True, null=True)),
                ("icon", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="blmf.servicecard",
                    ),
                ),
            ],
        ),
    ]
