# Generated by Django 6.0.2 on 2026-02-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactprops",
            name="instagram",
            field=models.CharField(max_length=200),
        ),
    ]
