# Generated by Django 6.0.2 on 2026-02-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0002_alter_contactprops_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecard",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicecard",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
