# Generated by Django 6.0.2 on 2026-02-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0003_alter_servicecard_content_alter_servicecard_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descriptionitem",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
