# Generated by Django 6.0.2 on 2026-02-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0004_alter_descriptionitem_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descriptionitem",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="homepage"),
        ),
        migrations.AlterField(
            model_name="servicecard",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="homepage"),
        ),
    ]
