# Generated by Django 6.0.2 on 2026-02-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0005_alter_descriptionitem_icon_alter_servicecard_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descriptionitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to="blmf.servicecard",
            ),
        ),
    ]
