# Generated by Django 6.0.2 on 2026-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0006_alter_descriptionitem_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecard",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
