# Generated by Django 6.0.2 on 2026-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blmf", "0007_alter_servicecard_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprops",
            name="top_page",
            field=models.BooleanField(default=False),
        ),
    ]
